name: Sync Submodules

on:
  repository_dispatch:
    types: [sync-submodules]

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Monorepo with submodules
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull latest changes in submodules
        run: |
          git submodule update --remote --merge

      - name: Commit updated submodule pointers
        run: |
          git config user.name "Uttkarsh08-Bot"
          git config user.email "uttkarsh08@users.noreply.github.com"
          git add android backend
          if git diff --cached --quiet; then
            echo "✅ Submodules are already up to date."
          else
            git commit -m "🔄 Auto-sync submodule pointers from Android/Backend"
            git push origin main
          fi
